# See https://docs.github.com/ja/repositories/releasing-projects-on-github/automatically-generated-release-notes#example-configuration
changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: 🐛 Bug Fixes
      labels: [bug]
    - title: 🔥 Deprecated
      labels: [deprecated]
    - title: ✨ New Feature
      labels: [enhancement]
    - title: ⚡️ Improvement
      labels: [improvement]
    - title: 📝 Documentation
      labels: [documentation]
    - title: ♻️ Refactoring
      labels: [refactoring]
    - title: ⛓️ Dependencies
      labels: [dependencies]
    - title: Other Changes
      labels: ["*"]
